---
apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: hello-world-sinatra
  namespace: officehours
  labels:
    app: hello-world-sinatra

spec:
  revisionHistoryLimit: 3
  replicas: 1

  template:
    metadata:
      name: hello-world-sinatra
      labels:
        app: hello-world-sinatra
    spec:
      containers:
      - name: hello-world-sinatra
        image: 602688267222.dkr.ecr.us-east-1.amazonaws.com/officehours/hello-world:dolsen
        imagePullPolicy: Always
        ports:
        - name: sinatra
          containerPort: 4567
        resources:
          requests:
            cpu: 0.3
            memory: 1Gi

